In [4]:
#Impoting pandas,numpy and matplotlib.pyplot.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# loading fishing data as pandas DataFrame, fishing then printing.
fishing='fishing_results.csv'
fishing_df=pd.read_csv(fishing)
fishing_df

,Year,Survey,Station,Latitude,Longitude,Area,Species,Total Number Caught,Mean Weight (kg)
0,2017,United States,1,58.778,-177.575,Bering Sea,Giant grenadier,1727.000000,3.590
1,2017,United States,1,58.778,-177.575,Bering Sea,Pacific cod,732.000000,2.923
2,2017,United States,1,58.778,-177.575,Bering Sea,Pacific halibut,25.000000,NaN
3,2017,United States,1,58.778,-177.575,Bering Sea,Rougheye rockfish,4.666667,2.379
4,2017,United States,1,58.778,-177.575,Bering Sea,Sablefish,171.000000,1.558
5,2017,United States,1,58.778,-177.575,Bering Sea,Shortraker rockfish,9.333333,0.736
6,2017,United States,1,58.778,-177.575,Bering Sea,Shortspine thornyhead,117.000000,0.824
7,2017,United States,2,58.620,-176.642,Bering Sea,Giant grenadier,2238.000000,3.590
8,2017,United States,2,58.620,-176.642,Bering Sea,Pacific cod,271.000000,3.561
9,2017,United States,2,58.620,-176.642,Bering Sea,Pacific halibut,25.000000,NaN
10,2017,United States,2,58.620,-176.642,Bering Sea,Rougheye rockfish,NaN,NaN
11,2017,United States,2,58.620,-176.642,Bering Sea,Sablefish,102.000000,1.655
12,2017,United States,2,58.620,-176.642,Bering Sea,Shortraker rockfish,2.000000,1.102
13,2017,United States,2,58.620,-176.642,Bering Sea,Shortspine thornyhead,25.000000,1.052
14,2017,United States,4,58.497,-175.670,Bering Sea,Giant grenadier,1308.000000,3.268
15,2017,United States,4,58.497,-175.670,Bering Sea,Pacific cod,298.000000,3.231
16,2017,United States,4,58.497,-175.670,Bering Sea,Pacific halibut,7.000000,NaN
17,2017,United States,4,58.497,-175.670,Bering Sea,Rougheye rockfish,8.000000,2.329
18,2017,United States,4,58.497,-175.670,Bering Sea,Sablefish,229.000000,1.465
19,2017,United States,4,58.497,-175.670,Bering Sea,Shortraker rockfish,11.000000,1.108
20,2017,United States,4,58.497,-175.670,Bering Sea,Shortspine thornyhead,71.000000,0.824
21,2017,United States,6,58.333,-174.312,Bering Sea,Giant grenadier,1880.000000,4.676
22,2017,United States,6,58.333,-174.312,Bering Sea,Pacific cod,695.000000,3.231
23,2017,United States,6,58.333,-174.312,Bering Sea,Pacific halibut,327.000000,NaN
24,2017,United States,6,58.333,-174.312,Bering Sea,Rougheye rockfish,NaN,NaN
25,2017,United States,6,58.333,-174.312,Bering Sea,Sablefish,143.000000,2.206
26,2017,United States,6,58.333,-174.312,Bering Sea,Shortraker rockfish,113.000000,1.265
27,2017,United States,6,58.333,-174.312,Bering Sea,Shortspine thornyhead,35.000000,1.419
28,2017,United States,8,57.628,-174.165,Bering Sea,Giant grenadier,2130.000000,3.590
29,2017,United States,8,57.628,-174.165,Bering Sea,Pacific cod,288.000000,4.099
...,...,...,...,...,...,...,...,...,...
20945,1979,Japan,97,58.468,-139.467,East Yakutat/Southeast,Pacific cod,24.000000,4.099
20946,1979,Japan,97,58.468,-139.467,East Yakutat/Southeast,Pacific halibut,18.000000,3.429
20947,1979,Japan,97,58.468,-139.467,East Yakutat/Southeast,Sablefish,562.000000,2.458
20948,1979,Japan,97,58.468,-139.467,East Yakutat/Southeast,Shortspine thornyhead,116.000000,0.431
20949,1979,Japan,101,57.188,-136.235,East Yakutat/Southeast,Giant grenadier,222.000000,NaN
20950,1979,Japan,101,57.188,-136.235,East Yakutat/Southeast,Pacific halibut,10.000000,NaN
20951,1979,Japan,101,57.188,-136.235,East Yakutat/Southeast,Sablefish,1576.000000,2.873
20952,1979,Japan,101,57.188,-136.235,East Yakutat/Southeast,Shortspine thornyhead,82.000000,0.388
20953,1979,Japan,103,56.383,-135.348,East Yakutat/Southeast,Giant grenadier,13.000000,NaN
20954,1979,Japan,103,56.383,-135.348,East Yakutat/Southeast,Pacific cod,96.000000,4.487
20955,1979,Japan,103,56.383,-135.348,East Yakutat/Southeast,Pacific halibut,57.000000,2.413
20956,1979,Japan,103,56.383,-135.348,East Yakutat/Southeast,Sablefish,931.000000,2.206
20957,1979,Japan,103,56.383,-135.348,East Yakutat/Southeast,Shortspine thornyhead,131.000000,0.312
20958,1979,Japan,105,55.558,-134.967,East Yakutat/Southeast,Giant grenadier,171.000000,NaN
20959,1979,Japan,105,55.558,-134.967,East Yakutat/Southeast,Sablefish,1961.000000,3.021
20960,1979,Japan,105,55.558,-134.967,East Yakutat/Southeast,Shortspine thornyhead,128.000000,0.476
20961,1979,Japan,106,55.347,-134.735,East Yakutat/Southeast,Giant grenadier,95.000000,NaN
20962,1979,Japan,106,55.347,-134.735,East Yakutat/Southeast,Pacific cod,175.000000,3.231
20963,1979,Japan,106,55.347,-134.735,East Yakutat/Southeast,Pacific halibut,77.000000,2.618
20964,1979,Japan,106,55.347,-134.735,East Yakutat/Southeast,Sablefish,1279.000000,2.329
20965,1979,Japan,106,55.347,-134.735,East Yakutat/Southeast,Shortspine thornyhead,165.000000,0.431
20966,1979,Japan,107,54.900,-134.287,East Yakutat/Southeast,Giant grenadier,173.000000,NaN
20967,1979,Japan,107,54.900,-134.287,East Yakutat/Southeast,Pacific cod,4.000000,NaN
20968,1979,Japan,107,54.900,-134.287,East Yakutat/Southeast,Sablefish,1174.000000,2.329
20969,1979,Japan,107,54.900,-134.287,East Yakutat/Southeast,Shortspine thornyhead,141.000000,0.476
20970,1979,Japan,108,54.450,-133.930,East Yakutat/Southeast,Giant grenadier,143.000000,NaN
20971,1979,Japan,108,54.450,-133.930,East Yakutat/Southeast,Pacific cod,2.000000,NaN
20972,1979,Japan,108,54.450,-133.930,East Yakutat/Southeast,Pacific halibut,1.000000,NaN
20973,1979,Japan,108,54.450,-133.930,East Yakutat/Southeast,Sablefish,628.000000,2.329
20974,1979,Japan,108,54.450,-133.930,East Yakutat/Southeast,Shortspine thornyhead,139.000000,0.525

In [6]:
#Dropping NaN values using dropna() and saving results as clean.
clean=fishing_df.dropna()
print(clean)

       Year         Survey  Station  Latitude  Longitude  \
0      2017  United States        1    58.778   -177.575
1      2017  United States        1    58.778   -177.575
3      2017  United States        1    58.778   -177.575
4      2017  United States        1    58.778   -177.575
5      2017  United States        1    58.778   -177.575
6      2017  United States        1    58.778   -177.575
7      2017  United States        2    58.620   -176.642
8      2017  United States        2    58.620   -176.642
11     2017  United States        2    58.620   -176.642
12     2017  United States        2    58.620   -176.642
13     2017  United States        2    58.620   -176.642
14     2017  United States        4    58.497   -175.670
15     2017  United States        4    58.497   -175.670
17     2017  United States        4    58.497   -175.670
18     2017  United States        4    58.497   -175.670
19     2017  United States        4    58.497   -175.670
20     2017  United States        4    58.497   -175.670
21     2017  United States        6    58.333   -174.312
22     2017  United States        6    58.333   -174.312
25     2017  United States        6    58.333   -174.312
26     2017  United States        6    58.333   -174.312
27     2017  United States        6    58.333   -174.312
28     2017  United States        8    57.628   -174.165
29     2017  United States        8    57.628   -174.165
31     2017  United States        8    57.628   -174.165
32     2017  United States        8    57.628   -174.165
33     2017  United States        8    57.628   -174.165
34     2017  United States        8    57.628   -174.165
35     2017  United States       10    56.828   -173.378
36     2017  United States       10    56.828   -173.378
...     ...            ...      ...       ...        ...
20931  1979          Japan       94    59.388   -142.163
20932  1979          Japan       94    59.388   -142.163
20933  1979          Japan       94    59.388   -142.163
20934  1979          Japan       94    59.388   -142.163
20936  1979          Japan       95    59.050   -141.343
20937  1979          Japan       95    59.050   -141.343
20938  1979          Japan       95    59.050   -141.343
20941  1979          Japan       96    58.685   -140.640
20942  1979          Japan       96    58.685   -140.640
20943  1979          Japan       96    58.685   -140.640
20945  1979          Japan       97    58.468   -139.467
20946  1979          Japan       97    58.468   -139.467
20947  1979          Japan       97    58.468   -139.467
20948  1979          Japan       97    58.468   -139.467
20951  1979          Japan      101    57.188   -136.235
20952  1979          Japan      101    57.188   -136.235
20954  1979          Japan      103    56.383   -135.348
20955  1979          Japan      103    56.383   -135.348
20956  1979          Japan      103    56.383   -135.348
20957  1979          Japan      103    56.383   -135.348
20959  1979          Japan      105    55.558   -134.967
20960  1979          Japan      105    55.558   -134.967
20962  1979          Japan      106    55.347   -134.735
20963  1979          Japan      106    55.347   -134.735
20964  1979          Japan      106    55.347   -134.735
20965  1979          Japan      106    55.347   -134.735
20968  1979          Japan      107    54.900   -134.287
20969  1979          Japan      107    54.900   -134.287
20973  1979          Japan      108    54.450   -133.930
20974  1979          Japan      108    54.450   -133.930

                         Area                Species  Total Number Caught  \
0                  Bering Sea        Giant grenadier          1727.000000
1                  Bering Sea            Pacific cod           732.000000
3                  Bering Sea      Rougheye rockfish             4.666667
4                  Bering Sea              Sablefish           171.000000
5                  Bering Sea    Shortraker rockfish             9.333333
6                  Bering Sea  Shortspine thornyhead           117.000000
7                  Bering Sea        Giant grenadier          2238.000000
8                  Bering Sea            Pacific cod           271.000000
11                 Bering Sea              Sablefish           102.000000
12                 Bering Sea    Shortraker rockfish             2.000000
13                 Bering Sea  Shortspine thornyhead            25.000000
14                 Bering Sea        Giant grenadier          1308.000000
15                 Bering Sea            Pacific cod           298.000000
17                 Bering Sea      Rougheye rockfish             8.000000
18                 Bering Sea              Sablefish           229.000000
19                 Bering Sea    Shortraker rockfish            11.000000
20                 Bering Sea  Shortspine thornyhead            71.000000
21                 Bering Sea        Giant grenadier          1880.000000
22                 Bering Sea            Pacific cod           695.000000
25                 Bering Sea              Sablefish           143.000000
26                 Bering Sea    Shortraker rockfish           113.000000
27                 Bering Sea  Shortspine thornyhead            35.000000
28                 Bering Sea        Giant grenadier          2130.000000
29                 Bering Sea            Pacific cod           288.000000
31                 Bering Sea      Rougheye rockfish             2.051282
32                 Bering Sea              Sablefish           101.000000
33                 Bering Sea    Shortraker rockfish            37.948718
34                 Bering Sea  Shortspine thornyhead            99.000000
35                 Bering Sea        Giant grenadier          2609.000000
36                 Bering Sea            Pacific cod           153.000000
...                       ...                    ...                  ...
20931            West Yakutat            Pacific cod           385.000000
20932            West Yakutat        Pacific halibut           151.000000
20933            West Yakutat              Sablefish           630.000000
20934            West Yakutat  Shortspine thornyhead           139.000000
20936            West Yakutat        Pacific halibut             5.000000
20937            West Yakutat              Sablefish           976.000000
20938            West Yakutat  Shortspine thornyhead            92.000000
20941            West Yakutat        Pacific halibut            53.000000
20942            West Yakutat              Sablefish          1035.000000
20943            West Yakutat  Shortspine thornyhead           103.000000
20945  East Yakutat/Southeast            Pacific cod            24.000000
20946  East Yakutat/Southeast        Pacific halibut            18.000000
20947  East Yakutat/Southeast              Sablefish           562.000000
20948  East Yakutat/Southeast  Shortspine thornyhead           116.000000
20951  East Yakutat/Southeast              Sablefish          1576.000000
20952  East Yakutat/Southeast  Shortspine thornyhead            82.000000
20954  East Yakutat/Southeast            Pacific cod            96.000000
20955  East Yakutat/Southeast        Pacific halibut            57.000000
20956  East Yakutat/Southeast              Sablefish           931.000000
20957  East Yakutat/Southeast  Shortspine thornyhead           131.000000
20959  East Yakutat/Southeast              Sablefish          1961.000000
20960  East Yakutat/Southeast  Shortspine thornyhead           128.000000
20962  East Yakutat/Southeast            Pacific cod           175.000000
20963  East Yakutat/Southeast        Pacific halibut            77.000000
20964  East Yakutat/Southeast              Sablefish          1279.000000
20965  East Yakutat/Southeast  Shortspine thornyhead           165.000000
20968  East Yakutat/Southeast              Sablefish          1174.000000
20969  East Yakutat/Southeast  Shortspine thornyhead           141.000000
20973  East Yakutat/Southeast              Sablefish           628.000000
20974  East Yakutat/Southeast  Shortspine thornyhead           139.000000

       Mean Weight (kg)
0                 3.590
1                 2.923
3                 2.379
4                 1.558
5                 0.736
6                 0.824
7                 3.590
8                 3.561
11                1.655
12                1.102
13                1.052
14                3.268
15                3.231
17                2.329
18                1.465
19                1.108
20                0.824
21                4.676
22                3.231
25                2.206
26                1.265
27                1.419
28                3.590
29                4.099
31                2.278
32                2.087
33                1.570
34                0.896
35                4.293
36                3.394
...                 ...
20931             2.635
20932             2.835
20933             2.591
20934             0.431
20936             4.101
20937             2.729
20938             0.388
20941             3.304
20942             2.729
20943             0.349
20945             4.099
20946             3.429
20947             2.458
20948             0.431
20951             2.873
20952             0.388
20954             4.487
20955             2.413
20956             2.206
20957             0.312
20959             3.021
20960             0.476
20962             3.231
20963             2.618
20964             2.329
20965             0.431
20968             2.329
20969             0.476
20973             2.329
20974             0.525

[17621 rows x 9 columns]

In [7]:
# Using all Bering Sea data after the year 1987. Saved results as clean1 and printed
clean1=clean[(clean.Area== 'Bering Sea') & (clean.Year >1987)]
print(clean1)

       Year         Survey  Station  Latitude  Longitude        Area  \
0      2017  United States        1    58.778   -177.575  Bering Sea
1      2017  United States        1    58.778   -177.575  Bering Sea
3      2017  United States        1    58.778   -177.575  Bering Sea
4      2017  United States        1    58.778   -177.575  Bering Sea
5      2017  United States        1    58.778   -177.575  Bering Sea
6      2017  United States        1    58.778   -177.575  Bering Sea
7      2017  United States        2    58.620   -176.642  Bering Sea
8      2017  United States        2    58.620   -176.642  Bering Sea
11     2017  United States        2    58.620   -176.642  Bering Sea
12     2017  United States        2    58.620   -176.642  Bering Sea
13     2017  United States        2    58.620   -176.642  Bering Sea
14     2017  United States        4    58.497   -175.670  Bering Sea
15     2017  United States        4    58.497   -175.670  Bering Sea
17     2017  United States        4    58.497   -175.670  Bering Sea
18     2017  United States        4    58.497   -175.670  Bering Sea
19     2017  United States        4    58.497   -175.670  Bering Sea
20     2017  United States        4    58.497   -175.670  Bering Sea
21     2017  United States        6    58.333   -174.312  Bering Sea
22     2017  United States        6    58.333   -174.312  Bering Sea
25     2017  United States        6    58.333   -174.312  Bering Sea
26     2017  United States        6    58.333   -174.312  Bering Sea
27     2017  United States        6    58.333   -174.312  Bering Sea
28     2017  United States        8    57.628   -174.165  Bering Sea
29     2017  United States        8    57.628   -174.165  Bering Sea
31     2017  United States        8    57.628   -174.165  Bering Sea
32     2017  United States        8    57.628   -174.165  Bering Sea
33     2017  United States        8    57.628   -174.165  Bering Sea
34     2017  United States        8    57.628   -174.165  Bering Sea
35     2017  United States       10    56.828   -173.378  Bering Sea
36     2017  United States       10    56.828   -173.378  Bering Sea
...     ...            ...      ...       ...        ...         ...
17256  1988          Japan       10    56.828   -173.378  Bering Sea
17257  1988          Japan       10    56.828   -173.378  Bering Sea
17258  1988          Japan       12    56.627   -172.353  Bering Sea
17259  1988          Japan       12    56.627   -172.353  Bering Sea
17260  1988          Japan       12    56.627   -172.353  Bering Sea
17261  1988          Japan       12    56.627   -172.353  Bering Sea
17262  1988          Japan       12    56.627   -172.353  Bering Sea
17263  1988          Japan       13    56.467   -171.452  Bering Sea
17264  1988          Japan       13    56.467   -171.452  Bering Sea
17265  1988          Japan       13    56.467   -171.452  Bering Sea
17266  1988          Japan       13    56.467   -171.452  Bering Sea
17267  1988          Japan       15    56.147   -170.732  Bering Sea
17268  1988          Japan       15    56.147   -170.732  Bering Sea
17269  1988          Japan       15    56.147   -170.732  Bering Sea
17270  1988          Japan       15    56.147   -170.732  Bering Sea
17271  1988          Japan       15    56.147   -170.732  Bering Sea
17272  1988          Japan       17    56.038   -169.618  Bering Sea
17273  1988          Japan       17    56.038   -169.618  Bering Sea
17274  1988          Japan       17    56.038   -169.618  Bering Sea
17275  1988          Japan       17    56.038   -169.618  Bering Sea
17276  1988          Japan       18    56.243   -169.172  Bering Sea
17277  1988          Japan       18    56.243   -169.172  Bering Sea
17278  1988          Japan       18    56.243   -169.172  Bering Sea
17279  1988          Japan       20    55.060   -168.802  Bering Sea
17280  1988          Japan       20    55.060   -168.802  Bering Sea
17281  1988          Japan       20    55.060   -168.802  Bering Sea
17282  1988          Japan       20    55.060   -168.802  Bering Sea
17284  1988          Japan       22    55.458   -168.004  Bering Sea
17285  1988          Japan       22    55.458   -168.004  Bering Sea
17286  1988          Japan       22    55.458   -168.004  Bering Sea

                     Species  Total Number Caught  Mean Weight (kg)
0            Giant grenadier          1727.000000             3.590
1                Pacific cod           732.000000             2.923
3          Rougheye rockfish             4.666667             2.379
4                  Sablefish           171.000000             1.558
5        Shortraker rockfish             9.333333             0.736
6      Shortspine thornyhead           117.000000             0.824
7            Giant grenadier          2238.000000             3.590
8                Pacific cod           271.000000             3.561
11                 Sablefish           102.000000             1.655
12       Shortraker rockfish             2.000000             1.102
13     Shortspine thornyhead            25.000000             1.052
14           Giant grenadier          1308.000000             3.268
15               Pacific cod           298.000000             3.231
17         Rougheye rockfish             8.000000             2.329
18                 Sablefish           229.000000             1.465
19       Shortraker rockfish            11.000000             1.108
20     Shortspine thornyhead            71.000000             0.824
21           Giant grenadier          1880.000000             4.676
22               Pacific cod           695.000000             3.231
25                 Sablefish           143.000000             2.206
26       Shortraker rockfish           113.000000             1.265
27     Shortspine thornyhead            35.000000             1.419
28           Giant grenadier          2130.000000             3.590
29               Pacific cod           288.000000             4.099
31         Rougheye rockfish             2.051282             2.278
32                 Sablefish           101.000000             2.087
33       Shortraker rockfish            37.948718             1.570
34     Shortspine thornyhead            99.000000             0.896
35           Giant grenadier          2609.000000             4.293
36               Pacific cod           153.000000             3.394
...                      ...                  ...               ...
17256        Pacific halibut            24.000000             2.725
17257              Sablefish           785.000000             3.175
17258        Giant grenadier           242.000000             4.293
17259            Pacific cod           465.000000             2.777
17260        Pacific halibut           150.000000             2.725
17261              Sablefish           640.000000             2.591
17262  Shortspine thornyhead             2.000000             1.634
17263        Giant grenadier            71.000000             4.676
17264            Pacific cod          1051.000000             2.923
17265        Pacific halibut            86.000000             2.514
17266              Sablefish          1087.000000             2.873
17267        Giant grenadier           246.000000             1.166
17268            Pacific cod          1327.000000             3.074
17269        Pacific halibut            25.000000             2.413
17270              Sablefish           589.000000             3.334
17271  Shortspine thornyhead             9.000000             1.419
17272        Giant grenadier           178.000000             4.293
17273            Pacific cod          1661.000000             3.914
17274        Pacific halibut            26.000000             2.413
17275              Sablefish           122.000000             2.591
17276            Pacific cod          1438.000000             3.074
17277        Pacific halibut           137.000000             1.336
17278              Sablefish           371.000000             2.087
17279        Giant grenadier            26.000000             2.965
17280            Pacific cod          1418.000000             3.735
17281        Pacific halibut             5.000000             1.948
17282              Sablefish            96.000000             2.591
17284            Pacific cod           649.000000             2.923
17285        Pacific halibut             7.000000             1.863
17286              Sablefish           137.000000             2.458

[1527 rows x 9 columns]

In [8]:
#Broke down dataframe clean1 into 4 colums,'Year','Area','Species' and 'Mean Weight (kg)
clean1[['Year', 'Area', 'Species', 'Mean Weight (kg)']]

       Year        Area                Species  Mean Weight (kg)
0      2017  Bering Sea        Giant grenadier             3.590
1      2017  Bering Sea            Pacific cod             2.923
3      2017  Bering Sea      Rougheye rockfish             2.379
4      2017  Bering Sea              Sablefish             1.558
5      2017  Bering Sea    Shortraker rockfish             0.736
6      2017  Bering Sea  Shortspine thornyhead             0.824
7      2017  Bering Sea        Giant grenadier             3.590
8      2017  Bering Sea            Pacific cod             3.561
11     2017  Bering Sea              Sablefish             1.655
12     2017  Bering Sea    Shortraker rockfish             1.102
13     2017  Bering Sea  Shortspine thornyhead             1.052
14     2017  Bering Sea        Giant grenadier             3.268
15     2017  Bering Sea            Pacific cod             3.231
17     2017  Bering Sea      Rougheye rockfish             2.329
18     2017  Bering Sea              Sablefish             1.465
19     2017  Bering Sea    Shortraker rockfish             1.108
20     2017  Bering Sea  Shortspine thornyhead             0.824
21     2017  Bering Sea        Giant grenadier             4.676
22     2017  Bering Sea            Pacific cod             3.231
25     2017  Bering Sea              Sablefish             2.206
26     2017  Bering Sea    Shortraker rockfish             1.265
27     2017  Bering Sea  Shortspine thornyhead             1.419
28     2017  Bering Sea        Giant grenadier             3.590
29     2017  Bering Sea            Pacific cod             4.099
31     2017  Bering Sea      Rougheye rockfish             2.278
32     2017  Bering Sea              Sablefish             2.087
33     2017  Bering Sea    Shortraker rockfish             1.570
34     2017  Bering Sea  Shortspine thornyhead             0.896
35     2017  Bering Sea        Giant grenadier             4.293
36     2017  Bering Sea            Pacific cod             3.394
...     ...         ...                    ...               ...
17256  1988  Bering Sea        Pacific halibut             2.725
17257  1988  Bering Sea              Sablefish             3.175
17258  1988  Bering Sea        Giant grenadier             4.293
17259  1988  Bering Sea            Pacific cod             2.777
17260  1988  Bering Sea        Pacific halibut             2.725
17261  1988  Bering Sea              Sablefish             2.591
17262  1988  Bering Sea  Shortspine thornyhead             1.634
17263  1988  Bering Sea        Giant grenadier             4.676
17264  1988  Bering Sea            Pacific cod             2.923
17265  1988  Bering Sea        Pacific halibut             2.514
17266  1988  Bering Sea              Sablefish             2.873
17267  1988  Bering Sea        Giant grenadier             1.166
17268  1988  Bering Sea            Pacific cod             3.074
17269  1988  Bering Sea        Pacific halibut             2.413
17270  1988  Bering Sea              Sablefish             3.334
17271  1988  Bering Sea  Shortspine thornyhead             1.419
17272  1988  Bering Sea        Giant grenadier             4.293
17273  1988  Bering Sea            Pacific cod             3.914
17274  1988  Bering Sea        Pacific halibut             2.413
17275  1988  Bering Sea              Sablefish             2.591
17276  1988  Bering Sea            Pacific cod             3.074
17277  1988  Bering Sea        Pacific halibut             1.336
17278  1988  Bering Sea              Sablefish             2.087
17279  1988  Bering Sea        Giant grenadier             2.965
17280  1988  Bering Sea            Pacific cod             3.735
17281  1988  Bering Sea        Pacific halibut             1.948
17282  1988  Bering Sea              Sablefish             2.591
17284  1988  Bering Sea            Pacific cod             2.923
17285  1988  Bering Sea        Pacific halibut             1.863
17286  1988  Bering Sea              Sablefish             2.458

[1527 rows x 4 columns]

In [9]:
clean1[clean1.Species== 'Sablefish']

,Year,Survey,Station,Latitude,Longitude,Area,Species,Total Number Caught,Mean Weight (kg)
4,2017,United States,1,58.778,-177.575,Bering Sea,Sablefish,171.0,1.558
11,2017,United States,2,58.620,-176.642,Bering Sea,Sablefish,102.0,1.655
18,2017,United States,4,58.497,-175.670,Bering Sea,Sablefish,229.0,1.465
25,2017,United States,6,58.333,-174.312,Bering Sea,Sablefish,143.0,2.206
32,2017,United States,8,57.628,-174.165,Bering Sea,Sablefish,101.0,2.087
39,2017,United States,10,56.828,-173.378,Bering Sea,Sablefish,183.0,1.655
46,2017,United States,12,56.627,-172.353,Bering Sea,Sablefish,256.0,1.558
53,2017,United States,13,56.467,-171.452,Bering Sea,Sablefish,37.0,1.972
60,2017,United States,15,56.147,-170.732,Bering Sea,Sablefish,16.0,2.329
67,2017,United States,17,56.038,-169.618,Bering Sea,Sablefish,129.0,2.206
74,2017,United States,18,56.243,-169.172,Bering Sea,Sablefish,210.0,1.465
81,2017,United States,20,55.060,-168.802,Bering Sea,Sablefish,1410.0,1.465
88,2017,United States,22,55.458,-168.004,Bering Sea,Sablefish,617.0,1.376
102,2017,United States,33,53.612,-168.298,Bering Sea,Sablefish,927.0,1.757
107,2017,United States,34,53.305,-168.898,Bering Sea,Sablefish,2014.0,1.655
1087,2015,United States,1,58.778,-177.575,Bering Sea,Sablefish,70.0,3.175
1094,2015,United States,2,58.620,-176.642,Bering Sea,Sablefish,10.0,4.407
1101,2015,United States,4,58.497,-175.670,Bering Sea,Sablefish,12.0,3.844
1108,2015,United States,6,58.333,-174.312,Bering Sea,Sablefish,9.0,2.591
1115,2015,United States,8,57.628,-174.165,Bering Sea,Sablefish,87.0,3.498
1122,2015,United States,10,56.828,-173.378,Bering Sea,Sablefish,97.0,3.498
1129,2015,United States,12,56.627,-172.353,Bering Sea,Sablefish,5.0,2.729
1136,2015,United States,13,56.467,-171.452,Bering Sea,Sablefish,115.0,3.334
1143,2015,United States,15,56.147,-170.732,Bering Sea,Sablefish,102.0,3.498
1150,2015,United States,17,56.038,-169.618,Bering Sea,Sablefish,26.0,3.021
1157,2015,United States,18,56.243,-169.172,Bering Sea,Sablefish,35.0,3.175
1164,2015,United States,20,55.060,-168.802,Bering Sea,Sablefish,315.0,2.873
1171,2015,United States,22,55.458,-168.004,Bering Sea,Sablefish,21.0,2.729
1178,2015,United States,32,53.772,-167.330,Bering Sea,Sablefish,851.0,2.329
1185,2015,United States,33,53.612,-168.298,Bering Sea,Sablefish,71.0,2.087
...,...,...,...,...,...,...,...,...,...
15783,1990,Japan,34,53.305,-168.898,Bering Sea,Sablefish,1004.0,2.873
16484,1989,Japan,1,58.778,-177.575,Bering Sea,Sablefish,322.0,3.175
16489,1989,Japan,2,58.620,-176.642,Bering Sea,Sablefish,100.0,2.729
16492,1989,Japan,4,58.497,-175.670,Bering Sea,Sablefish,415.0,2.729
16497,1989,Japan,6,58.333,-174.312,Bering Sea,Sablefish,394.0,2.873
16501,1989,Japan,8,57.628,-174.165,Bering Sea,Sablefish,280.0,3.498
16505,1989,Japan,10,56.828,-173.378,Bering Sea,Sablefish,10.0,2.206
16508,1989,Japan,12,56.627,-172.353,Bering Sea,Sablefish,7.0,2.087
16512,1989,Japan,13,56.467,-171.452,Bering Sea,Sablefish,1085.0,3.175
16517,1989,Japan,15,56.147,-170.732,Bering Sea,Sablefish,794.0,3.334
16522,1989,Japan,17,56.038,-169.618,Bering Sea,Sablefish,458.0,3.021
16526,1989,Japan,18,56.243,-169.172,Bering Sea,Sablefish,87.0,2.087
16529,1989,Japan,20,55.060,-168.802,Bering Sea,Sablefish,715.0,2.729
16533,1989,Japan,22,55.458,-168.004,Bering Sea,Sablefish,95.0,2.729
16537,1989,Japan,32,53.772,-167.330,Bering Sea,Sablefish,986.0,3.175
16542,1989,Japan,33,53.612,-168.298,Bering Sea,Sablefish,947.0,3.334
16544,1989,Japan,34,53.305,-168.898,Bering Sea,Sablefish,2668.0,2.729
17232,1988,Japan,1,58.778,-177.575,Bering Sea,Sablefish,355.0,2.729
17237,1988,Japan,2,58.620,-176.642,Bering Sea,Sablefish,137.0,2.729
17242,1988,Japan,4,58.497,-175.670,Bering Sea,Sablefish,439.0,2.873
17247,1988,Japan,6,58.333,-174.312,Bering Sea,Sablefish,654.0,3.021
17252,1988,Japan,8,57.628,-174.165,Bering Sea,Sablefish,336.0,3.334
17257,1988,Japan,10,56.828,-173.378,Bering Sea,Sablefish,785.0,3.175
17261,1988,Japan,12,56.627,-172.353,Bering Sea,Sablefish,640.0,2.591
17266,1988,Japan,13,56.467,-171.452,Bering Sea,Sablefish,1087.0,2.873
17270,1988,Japan,15,56.147,-170.732,Bering Sea,Sablefish,589.0,3.334
17275,1988,Japan,17,56.038,-169.618,Bering Sea,Sablefish,122.0,2.591
17278,1988,Japan,18,56.243,-169.172,Bering Sea,Sablefish,371.0,2.087
17282,1988,Japan,20,55.060,-168.802,Bering Sea,Sablefish,96.0,2.591
17286,1988,Japan,22,55.458,-168.004,Bering Sea,Sablefish,137.0,2.458

In [10]:
clean1.describe()

,Year,Station,Latitude,Longitude,Total Number Caught,Mean Weight (kg)
count,1527.000000,1527.000000,1527.000000,1527.000000,1527.000000,1527.000000
mean,2001.571709,14.986248,56.408119,-171.733008,337.792403,2.607275
std,9.099562,10.066317,1.680453,3.181567,517.511604,1.250205
min,1988.000000,1.000000,53.305000,-177.575000,0.875000,0.302000
25%,1993.000000,6.000000,55.458000,-174.312000,17.300000,1.524000
50%,2001.000000,13.000000,56.467000,-171.452000,102.000000,2.499000
75%,2009.000000,20.000000,58.333000,-168.898000,422.000000,3.498000
max,2017.000000,34.000000,58.778000,-167.330000,3190.000000,8.720000